"""
Django settings for RND project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6b2%g#s3s25&t1@31)2se!5cka)eeb30=2r4ed7ywak%iou@p!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'RND_APP',
    'corsheaders', # (cors -cross origin resource sharing )
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', # newly added for axcepting reqest from different domain cross origin resource sharing (cors)
]

#Specify Allowed Origins:
"""
In your settings, specify which origins are allowed to access your Django backend. 
You can configure this using the CORS_ALLOWED_ORIGINS setting. For development,
you can allow all origins by using a wildcard '*',
but in production, you should specify the actual origins that are allowed.
"""

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Allow requests from your frontend development server
    # Add other allowed origins here for production
]


ROOT_URLCONF = 'RND.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'newreact/build')],  # Templates files Directory 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RND.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# MongoDB ON Djongo Database connecting..................

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'local',  # The name of your MongoDB database
#         'HOST': 'localhost',  # The hostname where MongoDB is running
#         'PORT': 27017,  # The port MongoDB is listening on (default is 27017)
#         'OPTIONS': {
#             'asyncio': {
#                 'engine': 'motor.motor_asyncio.AsyncIOMotorEngine',  # The motor engine for asynchronous support
#             }
#         }
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'local',
#         'HOST': 'localhost',  # Usually 'localhost' for development
#         'PORT': 27017,              # MongoDB default port
#     }
# }




# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    # create a folder  path to your React app's static files directory later django will collect the files present here to STATIC_ROOT
      os.path.join(BASE_DIR, 'newreact/build/static'), 
    
   
]
# STATIC_ROOT = os.path.join(BASE_DIR,'Staticfiles2')
#STATIC_ROOT = os.path.join(BASE_DIR,) # path after creating a folder and run collectstatic command to collect staticfiles from STATICFILES_DIRS

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
